"""
Facebook Scheduler - Creates Facebook approval files at scheduled time
Uses Claude to generate professional content with diagrams
Does NOT post directly - creates approval file for human approval
"""
from datetime import datetime
from pathlib import Path
import sys
import subprocess
import re

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from scheduler.scheduler_db import update_post_status
from engine.logger import logger
from engine.diagram_generator import DiagramGenerator, DiagramTemplates


def generate_professional_facebook_post(user_prompt):
    """
    Use Claude to generate a professional Facebook post from user's prompt
    Also detects if diagram is needed and generates Mermaid code
    
    Args:
        user_prompt: Raw user input
        
    Returns:
        tuple: (post_text, mermaid_code or None)
    """
    try:
        logger.info(f"🤖 Generating professional Facebook post with Claude...")
        
        # Detect if user wants a diagram
        diagram_keywords = ['diagram', 'flowchart', 'workflow', 'architecture', 'process', 'pipeline', 'graph', 'funnel']
        needs_diagram = any(keyword in user_prompt.lower() for keyword in diagram_keywords)
        
        if needs_diagram:
            claude_prompt = f"""
You are a professional social media manager for a business company.

Generate a professional Facebook post based on this request:
"{user_prompt}"

Requirements:
- Professional and engaging tone
- Make it shareable and valuable
- Include emojis if appropriate (max 3)
- Focus on business value
- Keep it under 500 characters (Facebook allows more)
- Include call-to-action if appropriate

Also generate a Mermaid diagram code if the topic is technical (architecture, workflow, process, funnel, etc.)

Output format:
TEXT:
[your post here]

MERMAID:
[mermaid code here or "NONE" if not needed]
"""
        else:
            claude_prompt = f"""
You are a professional social media manager for a business company.

Generate a professional Facebook post based on this request:
"{user_prompt}"

Requirements:
- Professional and engaging tone
- Make it shareable and valuable
- Include emojis if appropriate (max 3)
- Focus on business value
- Keep it under 500 characters
- Include call-to-action if appropriate

Output ONLY the Facebook post text, nothing else.
"""
        
        claude_path = r"C:\Users\H P\AppData\Roaming\npm\claude.cmd"
        
        # Run claude with prompt via stdin
        result = subprocess.run(
            [claude_path, '-p'],
            input=claude_prompt,
            capture_output=True,
            text=True,
            timeout=120,
            shell=True
        )
        
        if result.stdout and len(result.stdout.strip()) >= 10:
            output = result.stdout.strip()
            logger.info(f"✅ Facebook post generated by Claude: {output[:50]}...")
            
            # Parse output for TEXT and MERMAID sections
            post_text = output
            mermaid_code = None
            
            if 'TEXT:' in output and 'MERMAID:' in output:
                # Extract sections
                text_match = re.search(r'TEXT:\s*(.+?)\n\n?MERMAID:', output, re.DOTALL)
                mermaid_match = re.search(r'MERMAID:\s*(.+?)$', output, re.DOTALL)
                
                if text_match:
                    post_text = text_match.group(1).strip()
                if mermaid_match:
                    mermaid_raw = mermaid_match.group(1).strip()
                    if mermaid_raw.upper() != 'NONE':
                        mermaid_code = mermaid_raw
            
            return post_text, mermaid_code
        else:
            logger.warning(f"Claude returned empty, using original prompt")
            return user_prompt, None
            
    except FileNotFoundError:
        logger.warning(f"Claude CLI not found, using original prompt")
        return user_prompt, None
    except Exception as e:
        logger.warning(f"Claude generation failed: {e}, using original prompt")
        return user_prompt, None


def create_facebook_approval_file(post_id, content, hashtags=None):
    """
    Create Facebook approval file in Pending Approval folder
    Uses Claude to generate professional content with diagrams

    This does NOT post to Facebook - it creates an approval file
    that requires human approval before posting (via execute_approved.py)

    Args:
        post_id: ID from scheduler database
        content: Post content (raw user input)
        hashtags: Optional hashtags

    Returns:
        approval_file_path: Path to created approval file, or None if failed
    """
    try:
        logger.info(f"📘 Creating Facebook approval file for scheduled post (ID: {post_id})")
        
        # FIRST: Use Claude to generate professional post and diagram
        professional_content, mermaid_code = generate_professional_facebook_post(content)
        
        # SECOND: Generate diagram image if Mermaid code provided
        diagram_path = None
        if mermaid_code:
            logger.info(f"🎨 Generating diagram from Mermaid code...")
            diagram_gen = DiagramGenerator()
            diagram_path = diagram_gen.generate_png(mermaid_code)
            if diagram_path:
                logger.info(f"✅ Diagram generated: {diagram_path}")
            else:
                logger.warning(f"⚠️ Diagram generation failed, posting text only")
        
        # Combine content and hashtags
        full_content = professional_content
        if hashtags:
            full_content = f"{professional_content}\n\n{hashtags}"

        # Create timestamp for filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        approval_filename = f"APPROVAL_facebook_post_{timestamp}.md"

        # Get Pending Approval folder
        pending_approval_folder = Path(__file__).parent.parent / "Pending Approval"
        pending_approval_folder.mkdir(exist_ok=True)

        approval_path = pending_approval_folder / approval_filename

        # Create approval file content
        approval_content = f"""---
type: facebook_approval
action: facebook_post
scheduled: true
original_schedule_id: {post_id}
---

# Facebook Post Approval (Scheduled)

## Original Request

{content}

## AI-Generated Content

{full_content}

"""
        
        # Add diagram info if generated
        if mermaid_code:
            approval_content += f"""
## AI-Generated Diagram

Diagram generated from Mermaid code:

```mermaid
{mermaid_code}
```

"""
        
        if diagram_path:
            approval_content += f"""
## Diagram Image

Image file: `{diagram_path}`

*This image will be attached when posting to Facebook*

"""

        approval_content += f"""---

## Instructions
1. Review the post above
2. Edit if needed
3. Approve: Move to `Approved/` folder (posts to Facebook automatically)
4. Reject: Move to `Rejected/` folder

---
*Created by AI Employee Vault Scheduler*
*Originally scheduled for: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
*Content enhanced by Claude AI*
*{'Diagram included ✅' if diagram_path else 'Text only'}*
"""

        # Write approval file
        approval_path.write_text(approval_content, encoding='utf-8')

        logger.info(f"✅ Facebook approval file created: {approval_filename}")
        logger.info(f"📁 Location: {approval_path}")
        logger.info(f"🖼️ Diagram: {'Included (' + diagram_path + ')' if diagram_path else 'None'}")

        # Update database with approval file path
        update_post_status(
            post_id,
            'processed',
            approval_file=str(approval_path)
        )

        return str(approval_path)

    except Exception as e:
        logger.error(f"❌ Failed to create Facebook approval file: {e}")
        update_post_status(post_id, 'failed', error_message=str(e))
        return None


def process_scheduled_facebook_post(post_id, content, hashtags=None):
    """
    Process a scheduled Facebook post - creates approval file

    Args:
        post_id: ID from scheduler database
        content: Post content
        hashtags: Optional hashtags

    Returns:
        success: True if approval file created successfully
    """
    approval_path = create_facebook_approval_file(post_id, content, hashtags)
    return approval_path is not None


# Test function
if __name__ == "__main__":
    print("🧪 Testing Facebook Scheduler with Diagrams...")
    print("=" * 60)

    # Test 1: Post with diagram
    print("\n📊 Test 1: Marketing funnel (should include diagram)")
    approval_path = create_facebook_approval_file(
        post_id=999,
        content="Create post about marketing funnel with diagram showing customer journey",
        hashtags="#Marketing #Sales #Funnel"
    )

    if approval_path:
        print(f"✅ Facebook scheduler test 1 passed!")
        print(f"📁 Approval file created at: {approval_path}")
    else:
        print("\n❌ Facebook scheduler test 1 failed!")
    
    # Test 2: Post without diagram
    print("\n📊 Test 2: Simple post (text only)")
    approval_path = create_facebook_approval_file(
        post_id=998,
        content="Check out our latest business automation features",
        hashtags="#Business #Automation"
    )

    if approval_path:
        print(f"✅ Facebook scheduler test 2 passed!")
        print(f"📁 Approval file created at: {approval_path}")
    else:
        print("\n❌ Facebook scheduler test 2 failed!")
    
    print("\n" + "=" * 60)
    print("✅ Facebook Scheduler Tests Complete!")
    print("📁 Check Pending Approval/ folder for output files")
    print("🖼️ Check Generated_Images/ folder for diagrams")
