"""
Twitter Scheduler - Creates Twitter approval files at scheduled time
Uses Claude to generate professional content with diagrams
Does NOT post directly - creates approval file for human approval
"""
from datetime import datetime
from pathlib import Path
import sys
import subprocess
import re

# Add parent to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from scheduler.scheduler_db import update_post_status
from engine.logger import logger
from engine.diagram_generator import DiagramGenerator, DiagramTemplates


def generate_professional_tweet(user_prompt):
    """
    Use Claude to generate a professional tweet from user's prompt
    Also detects if diagram is needed and generates Mermaid code
    
    Args:
        user_prompt: Raw user input
        
    Returns:
        tuple: (tweet_text, mermaid_code or None)
    """
    try:
        logger.info(f"🤖 Generating professional tweet with Claude...")
        
        # Detect if user wants a diagram
        diagram_keywords = ['diagram', 'flowchart', 'workflow', 'architecture', 'process', 'pipeline', 'graph']
        needs_diagram = any(keyword in user_prompt.lower() for keyword in diagram_keywords)
        
        if needs_diagram:
            claude_prompt = f"""
You are a professional social media manager for an AI automation company.

Generate a Twitter post based on this request:
"{user_prompt}"

Requirements:
- Maximum 280 characters (Twitter limit)
- Include 2-3 relevant hashtags
- Make it engaging and shareable
- Include emojis if appropriate (max 2)
- Professional but friendly tone

Also generate a Mermaid diagram code if the topic is technical (architecture, workflow, process, etc.)

Output format:
TEXT:
[your tweet here]

MERMAID:
[mermaid code here or "NONE" if not needed]
"""
        else:
            claude_prompt = f"""
You are a professional social media manager for an AI automation company.

Generate a Twitter post based on this request:
"{user_prompt}"

Requirements:
- Maximum 280 characters (Twitter limit)
- Include 2-3 relevant hashtags
- Make it engaging and shareable
- Include emojis if appropriate (max 2)
- Professional but friendly tone

Output ONLY the tweet text, nothing else.
"""
        
        claude_path = r"C:\Users\H P\AppData\Roaming\npm\claude.cmd"
        
        # Run claude with prompt via stdin
        result = subprocess.run(
            [claude_path, '-p'],
            input=claude_prompt,
            capture_output=True,
            text=True,
            timeout=120,
            shell=True
        )
        
        if result.stdout and len(result.stdout.strip()) >= 10:
            output = result.stdout.strip()
            logger.info(f"✅ Tweet generated by Claude: {output[:50]}...")
            
            # Parse output for TEXT and MERMAID sections
            tweet_text = output
            mermaid_code = None
            
            if 'TEXT:' in output and 'MERMAID:' in output:
                # Extract sections
                text_match = re.search(r'TEXT:\s*(.+?)\n\n?MERMAID:', output, re.DOTALL)
                mermaid_match = re.search(r'MERMAID:\s*(.+?)$', output, re.DOTALL)
                
                if text_match:
                    tweet_text = text_match.group(1).strip()
                if mermaid_match:
                    mermaid_raw = mermaid_match.group(1).strip()
                    if mermaid_raw.upper() != 'NONE':
                        mermaid_code = mermaid_raw
            
            # Ensure tweet fits Twitter limit
            if len(tweet_text) > 280:
                tweet_text = tweet_text[:277] + "..."
            
            return tweet_text, mermaid_code
        else:
            logger.warning(f"Claude returned empty, using original prompt")
            return user_prompt, None
            
    except FileNotFoundError:
        logger.warning(f"Claude CLI not found, using original prompt")
        return user_prompt, None
    except Exception as e:
        logger.warning(f"Claude generation failed: {e}, using original prompt")
        return user_prompt, None


def create_twitter_approval_file(post_id, content, hashtags=None, is_thread=False):
    """
    Create Twitter approval file in Pending Approval folder
    Uses Claude to generate professional content with diagrams

    This does NOT post to Twitter - it creates an approval file
    that requires human approval before posting (via execute_approved.py)

    Args:
        post_id: ID from scheduler database
        content: Tweet content (raw user input)
        hashtags: Optional hashtags
        is_thread: Whether this is a thread

    Returns:
        approval_file_path: Path to created approval file, or None if failed
    """
    try:
        logger.info(f"🐦 Creating Twitter approval file for scheduled post (ID: {post_id})")
        
        # FIRST: Use Claude to generate professional tweet and diagram
        professional_content, mermaid_code = generate_professional_tweet(content)
        
        # SECOND: Generate diagram image if Mermaid code provided
        diagram_path = None
        if mermaid_code:
            logger.info(f"🎨 Generating diagram from Mermaid code...")
            diagram_gen = DiagramGenerator()
            diagram_path = diagram_gen.generate_png(mermaid_code)
            if diagram_path:
                logger.info(f"✅ Diagram generated: {diagram_path}")
            else:
                logger.warning(f"⚠️ Diagram generation failed, posting text only")
        
        # Combine content and hashtags
        full_content = professional_content
        if hashtags:
            full_content = f"{professional_content}\n\n{hashtags}"

        # Create timestamp for filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        # Determine if thread or single post
        if is_thread:
            approval_filename = f"APPROVAL_twitter_thread_{timestamp}.md"
            action_type = "twitter_thread"
        else:
            approval_filename = f"APPROVAL_twitter_post_{timestamp}.md"
            action_type = "twitter_post"

        # Get Pending Approval folder
        pending_approval_folder = Path(__file__).parent.parent / "Pending Approval"
        pending_approval_folder.mkdir(exist_ok=True)

        approval_path = pending_approval_folder / approval_filename

        # Create approval file content
        approval_content = f"""---
type: twitter_approval
action: {action_type}
scheduled: true
original_schedule_id: {post_id}
---

# Twitter {'Thread' if is_thread else 'Post'} Approval (Scheduled)

## Original Request

{content}

## AI-Generated Content

{full_content}

"""
        
        # Add diagram info if generated
        if mermaid_code:
            approval_content += f"""
## AI-Generated Diagram

Diagram generated from Mermaid code:

```mermaid
{mermaid_code}
```

"""
        
        if diagram_path:
            approval_content += f"""
## Diagram Image

Image file: `{diagram_path}`

*This image will be attached when posting to Twitter*

"""

        approval_content += f"""---

## Instructions
1. Review the {'thread' if is_thread else 'post'} above
2. Edit if needed
3. Approve: Move to `Approved/` folder (opens Twitter for posting)
4. Reject: Move to `Rejected/` folder

---
*Created by AI Employee Vault Scheduler*
*Originally scheduled for: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
*Content enhanced by Claude AI*
*{'Diagram included ✅' if diagram_path else 'Text only'}*
"""

        # Write approval file
        approval_path.write_text(approval_content, encoding='utf-8')

        logger.info(f"✅ Twitter approval file created: {approval_filename}")
        logger.info(f"📁 Location: {approval_path}")
        logger.info(f"🖼️ Diagram: {'Included (' + diagram_path + ')' if diagram_path else 'None'}")

        # Update database with approval file path
        update_post_status(
            post_id,
            'processed',
            approval_file=str(approval_path)
        )

        return str(approval_path)

    except Exception as e:
        logger.error(f"❌ Failed to create Twitter approval file: {e}")
        update_post_status(post_id, 'failed', error_message=str(e))
        return None


def process_scheduled_twitter_post(post_id, content, hashtags=None, is_thread=False):
    """
    Process a scheduled Twitter post - creates approval file

    Args:
        post_id: ID from scheduler database
        content: Tweet content
        hashtags: Optional hashtags
        is_thread: Whether this is a thread

    Returns:
        success: True if approval file created successfully
    """
    approval_path = create_twitter_approval_file(post_id, content, hashtags, is_thread)
    return approval_path is not None


# Test function
if __name__ == "__main__":
    print("🧪 Testing Twitter Scheduler with Diagrams...")
    print("=" * 60)

    # Test 1: Post with diagram
    print("\n📊 Test 1: Technical post (should include diagram)")
    approval_path = create_twitter_approval_file(
        post_id=999,
        content="Create post about three-tier architecture with workflow diagram",
        hashtags="#Architecture #Tech #ThreeTier",
        is_thread=False
    )

    if approval_path:
        print(f"✅ Twitter scheduler test 1 passed!")
        print(f"📁 Approval file created at: {approval_path}")
    else:
        print("\n❌ Twitter scheduler test 1 failed!")
    
    # Test 2: Post without diagram
    print("\n📊 Test 2: Simple post (text only)")
    approval_path = create_twitter_approval_file(
        post_id=998,
        content="Check out our new AI automation service",
        hashtags="#AI #Automation",
        is_thread=False
    )

    if approval_path:
        print(f"✅ Twitter scheduler test 2 passed!")
        print(f"📁 Approval file created at: {approval_path}")
    else:
        print("\n❌ Twitter scheduler test 2 failed!")
    
    print("\n" + "=" * 60)
    print("✅ Twitter Scheduler Tests Complete!")
    print("📁 Check Pending Approval/ folder for output files")
    print("🖼️ Check Generated_Images/ folder for diagrams")
